#!/bin/env fish

set PROG ./hs2bf
set FILE test/Halt.hs

function compile
    echo "== $argv[1] =="
    eval $PROG --make $FILE $argv[2]
    echo -e "\n\n"
end
    

ghc --make Main -O -o $PROG;
and compile Core -Sc;
and compile GMachine -Sg;
and compile SAM -Ss;
and compile BFM -Sm;
and compile BFC -Sk;
and compile BF -Sb



