#!/bin/env fish

HsColour -print-css > doc/hscolour.css

for i in *.hs
    HsColour -odoc/$i.html -css -anchor $i
end

haddock -h --source-module="%F.html" --source-entity="%F.html#line-%L" -o doc *.hs
